// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANi1wD9O6YcOW4QyS5cN9F3JnzPFMO3cM',
    appId: '1:984329879853:web:4452947f13fe064629d3a4',
    messagingSenderId: '984329879853',
    projectId: 'giftme-2a991',
    authDomain: 'giftme-2a991.firebaseapp.com',
    storageBucket: 'giftme-2a991.appspot.com',
    measurementId: 'G-45Q2TV2ZFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDFOD7-3SGVC9-67t25ZWDw3MgeGG3_Y',
    appId: '1:984329879853:android:517fcb7f1956b5e129d3a4',
    messagingSenderId: '984329879853',
    projectId: 'giftme-2a991',
    storageBucket: 'giftme-2a991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByp6AxxvkLGyAwS46IW1uHk8LAxlmL8rY',
    appId: '1:984329879853:ios:3208a3281be49d7d29d3a4',
    messagingSenderId: '984329879853',
    projectId: 'giftme-2a991',
    storageBucket: 'giftme-2a991.appspot.com',
    iosBundleId: 'com.codeone.giftme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByp6AxxvkLGyAwS46IW1uHk8LAxlmL8rY',
    appId: '1:984329879853:ios:338c2facd7b7871c29d3a4',
    messagingSenderId: '984329879853',
    projectId: 'giftme-2a991',
    storageBucket: 'giftme-2a991.appspot.com',
    iosBundleId: 'com.codeone.giftme.RunnerTests',
  );
}
